name: ShellLint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE so your job can access it
      - uses: actions/checkout@v2
      # Lint bash scripts
      - name: Shell Linter
        uses: azohra/shell-linter@v0.4.0
        with:
          path: "src/*.bashrc, src/**/*.bashrc"
